
window.onload=function(){var ismoving=false;var pageH=document.documentElement.clientHeight;var allheight=document.documentElement.scrollHeight;var scrollFunc=function(e){e=e||window.event;if(ismoving){return;}else{if(e.wheelDelta>0||e.detail<0){var current=window.pageYOffset;if(current==0){return;}
pageScroll(-1,current);}
if(e.wheelDelta<0||e.detail>0){var current=window.pageYOffset;if(current==allheight-pageH){return;}
pageScroll(1,current);}}}
window.onresize=function(){pageH=document.documentElement.clientHeight;}
if(document.addEventListener){document.addEventListener('DOMMouseScroll',scrollFunc,false);}
if(document.attachEvent){document.attachEvent('onmousewheel',scrollFunc);}
window.onmousewheel=document.onmousewheel=scrollFunc;var timer=null;function pageScroll(speed,current){ismoving=true;if(speed>0){var allH=current+pageH;timer=setInterval(function(){var cur=window.pageYOffset;window.scrollTo(0,cur+speed);if(cur>(allH-(pageH/2))){speed=speed-1;}else{speed=speed+1;}
if(cur>=allH){clearInterval(timer);window.scrollTo(0,allH);ismoving=false;}},15)}else{var allH=current-pageH;timer=setInterval(function(){var cur=window.pageYOffset;window.scrollTo(0,cur+speed);if(cur<(allH+(pageH/2))){speed=speed+1;}else{speed=speed-1;}
if(cur<=allH){clearInterval(timer);window.scrollTo(0,allH);ismoving=false;}},15)}}
var cite=document.getElementById('cite');var clickMe=document.getElementById('clickMe');clickMe.onclick=function(){cite.innerHTML="<p class='addCite'>我叫<span style='color:#f29d17;'>孙星星</span>，所以我洋气的英文名是DoubleStar。<br>我是个girl，一个来自<img src='images/china.png' alt='中国'>安徽安庆的girl。<br>我毕业于安徽理工大学，哦，是即将毕业。<br>我的专业是信息管理与信息系统。<br>嗯~~还有什么呢……</p>";clickMe.innerHTML='Next';clickMe.onclick=function(){cite.innerHTML="<p class='addCite' style='font:10px;'>对了，大学三年里我曾学过<span style='color:#f29d17;'>WEB开发技术，PHP+MySQL项目<br>实例开发，JSP原理及应用，计算机网络，C语言程序设计，<br>管理学</span>等课程。我曾获得校三等奖学金和三好学生称号，<br>有英语四级和计算机三级证书。</p>";clickMe.innerHTML='Continue';clickMe.onclick=function(){cite.innerHTML="<p class='addCite' style='font:10px;'>生活中，我的爱好挺多。动漫，电影，练书法，游戏，音乐，<br>阅读，刻章，逛网站……<br>反正我就是个喜欢捣鼓生活的人。<br><img id='love1' src='images/love1.jpg' alt='love1'>&nbsp;<img id='love2' src='images/love2.jpg' alt='love2'>&nbsp;<img id='love3' src='images/love3.jpg' alt='love3'>&nbsp;<img id='love4' src='images/love4.jpg' alt='love4'><br><span style='display:none;color:#f29d17;' id='introduce'><span></p>";var introduce=document.getElementById('introduce');var love1=document.getElementById('love1');var love2=document.getElementById('love2');var love3=document.getElementById('love3');var love4=document.getElementById('love4');function mouseOver(love,str){love.onmouseover=function(){introduce.style.display='block';introduce.innerHTML=str;}
love.onmouseout=function(){introduce.innerHTML='';}}
mouseOver(love1,'这部漫画叫《镖人》，我追的很辛苦！');mouseOver(love2,'这是日常练笔，丑萌丑萌的~');mouseOver(love3,'这款生存游戏叫“饥荒”，可惜活不过10天~');mouseOver(love4,'准备为自己刻个章的，仍在练习中！');clickMe.innerHTML='Finally';clickMe.onclick=function(){cite.innerHTML="<p class='addCite' style='font:10px;'>最后，报上我的联系方式。<br>手机：<span style='color:#f29d17;'>18855467493</span>，<br>e-mail:<span style='color:#f29d17;'>xingxing2huo@163.com</span>。<br>好了，以上就是我的一些个人信息了。</p>"
clickMe.innerHTML='End';clickMe.onclick=function(){cite.innerHTML="<p class='addCite' style='font:10px;'>已经是<span style='color:#f29d17;'>End</span>了哦,怎么还点呢？<br>请继续看我的web吧~<br>Thank you~</p>"
clickMe.style.display='none';}}}}}
var board=document.getElementById('board');var s1=document.getElementById('s1');var s2=document.getElementById('s2');var s3=document.getElementById('s3');var s4=document.getElementById('s4');var s5=document.getElementById('s5');var s6=document.getElementById('s6');var s7=document.getElementById('s7');function onClick(s,str){s.onclick=function(){board.style.display='block';board.innerHTML=str;}}
onClick(s1,'<p class="addBoard_time">2015年4月<br><br><span>大一下学期，加入前端小组。<br>在组长的带领下学习HTML5+css3，<br>从此，前端和我有了一些不能不说<br>的故事……</span></p><span class="addBoard_esc">P.S. 点击弹出面板任意处即可退出</span>');onClick(s2,'<p class="addBoard_time">2015年9月<br><br><span>担任前端小组副组长，向新人介绍<br>photoshop基础知识。<br><br><img src="images/ps.png" alt="ps"></span></p><span class="addBoard_esc">P.S. 点击弹出面板任意处即可退出</span>');onClick(s3,'<h1 class="addBoard"><p class="addBoard_time">2016年3月<br><br><span>决定朝着前端工程师努力，重新<br>开始学习前端相关知识.<br><br><img src="images/hcj.png" alt="hcj"></span></p><span class="addBoard_esc">P.S. 点击弹出面板任意处即可退出</span></h1>');onClick(s4,'<p class="addBoard_time">2017年1月<br><br><span>花费大概两周时间，完成信息网站<br>的开发与设计的课程设计。我和<br>partner合作制作一个有关校园<br>二手物品买卖的信息网站，主要以<br>修改模板为主。使用<br>html+css+php+mysql知识，后台<br>实现增删改查等基础功能。我主要<br>负责代码修改。</span><br><br><img src="images/web3.jpg" alt="web3"></p><span class="addBoard_esc">P.S. 点击弹出面板任意处即可退出</span>');onClick(s5,'<h1 class="addBoard"><p class="addBoard_time">2016年3月<br><br><span>JSP原理及其应用的课程设计，我<br>写了一个个人BBS，使用html+css+jquery+jsp+Access等<br>知识，实现登录、注册、留言、<br>发帖等基本功能，有简单的交互界面。</span><br><br><img src="images/bbs.jpg" alt="BBS"></p><span class="addBoard_esc">P.S. 点击弹出面板任意处即可退出</span></h1>');onClick(s6,'<h1 class="addBoard"><p class="addBoard_time">2016年9月<br><br><span>开始模仿简单的静态网站，主要<br>练习css+div的页面布局。练习了<br>几个类型的网页，有电商网页，<br>企业网页，娱乐网页等。</span><br><br><img src="images/web1.jpg" alt="web1"></p><span class="addBoard_esc">P.S. 点击弹出面板任意处即可退出</span></h1>');onClick(s7,'<p class="addBoard_time">2017年7月<br><br><span>三大结束，即将毕业。留校近20天，<br>完成了这个网页的制作。写到这里，<br>突然发现，原来我的大学就这样<br>结束了。愿吾，历经千帆，归来<br>仍少年。<br>In me the tiger sniffs the rose.</span><br><br><img src="images/web2.jpg" alt="web2"></p><span class="addBoard_esc">P.S. 点击弹出面板任意处即可退出</span>');board.onclick=function(){board.style.display='none';}
var skill=document.getElementById('skill');var add_shadow=document.getElementById('add_shadow');var before=document.getElementById('change_before');var after=document.getElementById('change_after');var lead=document.getElementById('lead');var enter=document.getElementById('enter');enter.onclick=function(){skill.style.background='none';before.style.display='none';after.style.display='block';function $(id){return document.getElementById(id);}
var word_all=document.getElementById('word_all');var dong_btn=document.getElementById('dong_btn');var continue1=document.getElementById('continue');dong_btn.onclick=function(){$('word1').style.display='block';setTimeout(function(){$('word2').style.display='block';$('pic_1').style.display='block';},1000);setTimeout(function(){$('word3').style.display='block';$('word10').style.display='block';$('pic_4').style.display='block';},2000);setTimeout(function(){$('word4').style.display='block';$('pic_6').style.display='block';},3000);setTimeout(function(){$('word5').style.display='block';$('word9').style.display='block';$('pic_2').style.display='block';},4000);setTimeout(function(){$('word6').style.display='block';$('pic_7').style.display='block';},5000);setTimeout(function(){$('word7').style.display='block';$('word11').style.display='block';$('pic_3').style.display='block';},6000);setTimeout(function(){$('word8').style.display='block';$('pic_5').style.display='block';},7000);setTimeout(function(){$('word12').style.display='block';},8000);setTimeout(function(){$('word13').style.display='block';$('pic_8').style.display='block';add_shadow.style.display='block';dong_btn.style.display='none';continue1.style.display='block';continue1.onclick=function(){skill.style.background='url(images/bg.png) no-repeat center';before.style.display='block';after.style.display='none';enter.style.display='none';lead.className='addLead';lead.innerHTML="<p class='addLead'>Give me a chance,<br>I will send infinite<br> starlight!<br>Thank You!</p>";}},9000);}}}